name: CI

on:
  push:
    paths:
      - '**'
    branches:
      - '**'
    tags:
      - '*.*.*'
  workflow_dispatch:

env:
  ARTIFACT_NAME: astolfo-bot

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Setup Yarn
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Copy example .dev.vars
        run: cp --verbose --archive .dev.vars.example .dev.vars

      - name: Generate Cloudflare Workers types
        run: yarn types

      - name: Build source code
        run: yarn build

      - name: Deploy to Cloudflare Workers
        if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: yarn deploy

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: dist

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
    permissions:
      contents: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: dist

      - name: Archive artifact
        run: |
          zip --recurse-paths ${{ env.ARTIFACT_NAME }}.zip dist
          tar --verbose --create --gzip --file ${{ env.ARTIFACT_NAME }}.tar.gz dist
          tar --verbose --create --xz --file ${{ env.ARTIFACT_NAME }}.tar.xz dist

      - name: Calculate checksums
        run: |
          md5sum ${{ env.ARTIFACT_NAME }}.zip ${{ env.ARTIFACT_NAME }}.tar.gz ${{ env.ARTIFACT_NAME }}.tar.xz > MD5SUMS.txt
          sha1sum ${{ env.ARTIFACT_NAME }}.zip ${{ env.ARTIFACT_NAME }}.tar.gz ${{ env.ARTIFACT_NAME }}.tar.xz > SHA1SUMS.txt
          sha256sum ${{ env.ARTIFACT_NAME }}.zip ${{ env.ARTIFACT_NAME }}.tar.gz ${{ env.ARTIFACT_NAME }}.tar.xz > SHA256SUMS.txt
          sha512sum ${{ env.ARTIFACT_NAME }}.zip ${{ env.ARTIFACT_NAME }}.tar.gz ${{ env.ARTIFACT_NAME }}.tar.xz > SHA512SUMS.txt

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: ${{ github.ref_name }}
          files: |
            ${{ env.ARTIFACT_NAME }}.zip
            ${{ env.ARTIFACT_NAME }}.tar.gz
            ${{ env.ARTIFACT_NAME }}.tar.xz
            MD5SUMS.txt
            SHA1SUMS.txt
            SHA256SUMS.txt
            SHA512SUMS.txt
          token: ${{ secrets.GITHUB_TOKEN }}
